<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmhRepository extends EntityRepository
{

    public function findCmh($id) {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('AppBundle:Cmh', 'c')
            ->where('c.user = :id')
            ->setParameter('id', $id)
            ->getQuery();
        return $qb->getQuery()->getResult();
    }

    public function findCmhWithDate($user, $start_date, $end_date) {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('AppBundle:Cmh', 'c')
            ->join('c.testgame', 't')
            ->where($qb->expr()->between(
                't.gamedates',
                ':from',
                ':to'
            ))
            ->andWhere('c.user = :id')
            ->orderBy('t.gamedates', 'ASC')
            ->setParameters(array(
                'id' => $user,
                'from' => $start_date,
                'to' => $end_date,
            ));

        return $qb->getQuery()->getResult();

    }
}
