<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findHighlights()
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('AppBundle:User', 'u')

            ->getQuery();
        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }

    public function findHighlightUserAction()
    {   
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('h')
            ->from('AppBundle:User')
            ->where('h.name = :highlight_user')
            ->setParameter('highlight_user', 'David')
            ->getQuery();
        return $qb->getQuery()->getArrayResult();
    }
}
